### ISSUE TITLE
[Suggestion] Normalization replacing constants in SQL stmt with '?' characters

### ISSUE THREAD

**Issue by stbaker517** [pganalyze/pg_query_go#118]
Hi. before beginning thanks for providing great query parse as an open source.

I wonder if you guys have any plan about replacing constants in SQL statement with  '?' characters in Normalize function as you annotated on the [pg_query_go](https://github.com/pganalyze/pg_query_go)'s Normalize function.

I'm currently on a project that collects all the sql query from different dbms and normalize(abstract)s sensitive constants so that  we can figure out which queries become SLOW QUERY.

I hope that pg_query of pg_query_go support normalization replacing constants in SQL stmt with '?' characters just like how pt-query-digest's normalizations works

If you are lack of resources(e.g.  focusing on other prior projects), I'm willing to make a PR for this.

Thank you for reading.

with my best regards.

**Comment by lfittl** [comment]
Hi @stbaker517 - thanks for your inquiry!

We intentionally do not use "?" in the normalize function (that's how it used to work, many releases ago), because "?" is a valid operator in Postgres, and as such normalized statements are ambiguous if you use it as a replacement character.

If you have a use case where you're looking to have "?" instead of "$1", "$2", etc. we recommend rewriting the result of the normalize function instead.

Hope that makes sense & good luck with your project!

**Comment by stbaker517** [comment]
Hi @lfittl . Thank you for your quick replying!

I'll follow you suggestion.

Thank you.
