### ISSUE TITLE
Structed error call back

### ISSUE THREAD

**Issue by mhkarimi1383** [pganalyze/pg_query_go#75]
Hi
I need to translate parse errors to pgproto error responses with the struct below

```go
type ErrorResponse struct {
	Severity            string
	SeverityUnlocalized string // only in 9.6 and greater
	Code                string
	Message             string
	Detail              string
	Hint                string
	Position            int32
	InternalPosition    int32
	InternalQuery       string
	Where               string
	SchemaName          string
	TableName           string
	ColumnName          string
	DataTypeName        string
	ConstraintName      string
	File                string
	Line                int32
	Routine             string

	UnknownFields map[byte]string
}
```

but I was not able to find a way to query parse errors (like invalid queries, etc.)

**Comment by mhkarimi1383** [comment]
something like https://github.com/Shyp/go-dberror

**Comment by lfittl** [comment]
@mhkarimi1383 Can you describe a bit more what your use case is?

Technically some of this information is available (see the complete error object in [libpg_query](https://github.com/pganalyze/libpg_query/blob/15-latest/pg_query.h#L7)), but today we don't use it in the Go library:

https://github.com/pganalyze/pg_query_go/blob/main/parser/parser.go#L82

We could expand that error handling, but it would require a bit of an API redesign, so it would be good to understand a bit better what you're trying to do. Note that some of this information (e.g. SchemaName, etc) is not available because pg_query works with the raw parse tree (i.e. without parse analysis that maps to actual database objects).

**Comment by mhkarimi1383** [comment]
I'm working on a project and I want to return that error to user directly without sending that query to postgres so I need full structured error

**Comment by lfittl** [comment]
@mhkarimi1383 Makes sense - just saw your pg_pro project on your GitHub profile - that looks like a cool project!

This actually was pretty straightforward to add, I just did a quick try at this in #76 

Do you want to test that PR and see whether that solves your use case? (as mentioned this is not all the possible error fields, but for basic errors like "this query fails to parse" it should match what Postgres itself would return to a client, except for the SQL error code, which is generated outside of the part of Postgres we currently work with -- I believe that's represented as `Code` in your struct above)

**Comment by mhkarimi1383** [comment]
Thanks
I will test as I get into my system

**Comment by mhkarimi1383** [comment]
How can I test that?

I'm getting error below while trying to upgrade

```bash
go get -u github.com/pganalyze/pg_query_go/v2@structured-errors
go: github.com/pganalyze/pg_query_go/v2@structured-errors: github.com/pganalyze/pg_query_go/v2@v2.2.1-0.20230222080459-106c8c69f1db: invalid version: go.mod has non-.../v2 module path "github.com/pganalyze/pg_query_go/v4" (and .../v2/go.mod does not exist) at revision 106c8c69f1db
```

**Comment by mhkarimi1383** [comment]
@lfittl Worked thanks, but I was not able to map `Funcname` to one of those fields in that `struct`, also I mapped `Context` field to `Details`

**Comment by mhkarimi1383** [comment]
@lfittl any updates?
